FROM alpine:latest

RUN apk add --no-cache curl

CMD ["curl", "-O", "http://ipv4.download.thinkbroadband.com/5MB.zip"]
# CMD ["curl", "-O", "http://azspdcentralus.blob.core.windows.net/private/100MB.bin"]
# CMD ["curl", "-O", "http://speedtest.dallas.linode.com/100MB-dallas.bin"]
# CMD ["curl", "-O", "http://speed.hetzner.de/100MB.bin"]
